export const ALBUM_FETCH_SUCCESS = 'ALBUM_FETCH_SUCCESS';
export const ALBUM_FETCH_FAILED = 'ALBUM_FETCH_FAILED';
export const SONGS_FETCH_SUCCESS = 'SONGS_FETCH_SUCCESS';
export const SONGS_FETCH_FAILED = 'SONGS_FETCH_FAILED';